# Generated by Django 3.1.2 on 2021-07-29 23:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date du match')),
                ('season', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Saison')),
                ('is_won', models.BooleanField(default=False, verbose_name='Partie gagnée')),
            ],
            options={
                'verbose_name': 'Partie',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=64, verbose_name='Pseudo')),
                ('pokemon', models.CharField(choices=[('Attacker', (('GARDEVOIR', 'Gardevoir'), ('PIKACHU', 'Pikachu'), ('GRENINJA', 'Greninja'), ('VENUSAUR', 'Venusaur'), ('A_NINETALES', 'Alolan Ninetales'), ('CRAMORANT', 'Cramorant'), ('CINDERACE', 'Cinderace'))), ('Speedster', (('ZERAORA', 'Zeraora'), ('TALONFLAME', 'Talonflame'), ('ABSOL', 'Absol'), ('GENGAR', 'Gengar'))), ('All-rounder', (('CHARIZARD', 'Charizard'), ('LUCARIO', 'Lucario'), ('MACHAMP', 'Machamp'), ('GARCHOMP', 'Garchomp'))), ('Defender', (('SNORLAX', 'Snorlax'), ('CRUSTLE', 'Crustle'), ('SLOWBRO', 'Slowbro'))), ('Supporter', (('ELDEGOSS', 'Eldegoss'), ('MR_MIME', 'Mr. Mime'), ('WIGGLYTUFF', 'Wigglytuff')))], max_length=64, verbose_name='Pokémon joué')),
                ('is_opponent', models.BooleanField(verbose_name='Joueur adverse')),
                ('scored', models.PositiveIntegerField(verbose_name='Points marqués')),
                ('kills', models.PositiveIntegerField(verbose_name='Nombre de KOs')),
                ('assists', models.PositiveIntegerField(verbose_name="Nombre d'assists")),
                ('result', models.PositiveIntegerField(verbose_name='Note globale')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.game')),
            ],
            options={
                'verbose_name': 'Joueur',
            },
        ),
    ]
