# Generated by Django 3.2.5 on 2021-08-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', 'game_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='score_allies',
            field=models.PositiveIntegerField(verbose_name='Score allié'),
        ),
        migrations.AlterField(
            model_name='game',
            name='score_opponents',
            field=models.PositiveIntegerField(verbose_name='Score opposants'),
        ),
    ]
