# Generated by Django 5.0.2 on 2024-02-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', 'pokemon_fix_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_forfeit',
            field=models.BooleanField(default=False, verbose_name='Forfait'),
        ),
    ]
