# Generated by Django 3.2.5 on 2021-08-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', 'pokemon_blissey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='category',
            field=models.CharField(choices=[('A', 'Attacker'), ('SS', 'Speedster'), ('AR', 'All-rounder'), ('D', 'Defender'), ('S', 'Supporter')], max_length=5, verbose_name='Catégorie'),
        ),
    ]
