# Generated by Django 3.2.5 on 2021-08-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_auto_20210801_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teammate',
            fields=[
                ('pseudo', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='Pseudo')),
            ],
            options={
                'verbose_name': 'Coéquipier',
            },
        ),
    ]
