# Generated by Django 5.0.2 on 2024-02-29 12:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def populate_seasons(apps, schema_editor):
    """
    Populate with existing seasons.
    """

    Season = apps.get_model("stats", "Season")
    Game = apps.get_model("stats", "Game")
    for i in Game.objects.values_list("season", flat=True).distinct().order_by():
        Season.objects.create(number=i).save()


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_game_is_forfeit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('number', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Numéro de saison')),
            ],
            options={
                'verbose_name': 'Saison',
            },
        ),
        migrations.RunPython(populate_seasons),
        migrations.AlterField(
            model_name='game',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stats.season'),
        ),
    ]
