# Generated by Django 5.0.2 on 2024-02-29 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_season_alter_game_season'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'get_latest_by': 'date', 'verbose_name': 'Partie'},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'get_latest_by': 'number', 'verbose_name': 'Saison'},
        ),
    ]
