# Generated by Django 3.2.5 on 2021-08-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20210803_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nom')),
                ('category', models.CharField(choices=[('A', 'Attacker'), ('S', 'Speedster'), ('AR', 'All-rounder'), ('D', 'Defender'), ('S', 'Supporter')], max_length=5, verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Pokémon',
            },
        ),
    ]
